// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vffhocyuwipbpjiuzwju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmZmhvY3l1d2lwYnBqaXV6d2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTYzMTEsImV4cCI6MjA2MzgzMjMxMX0.bmfBBwndYZLUf32uNPFfVAp2MowGIRv8Efe1EPC9K38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);